#!/bin/bash

# Adds hibernate functionality to Ubuntu laptop.

echo -n "Are you sure? [Y/n]"
read answer
if [ "$answer" = "y" ] | [ "$answer" = "Y" ] | [ "$answer" = "" ]; then
	echo "Hibernating..."
	dbus-send --system --print-reply \
	--dest="org.freedesktop.UPower" \
	/org/freedesktop/UPower \
	org.freedesktop.UPower.Hibernate > /dev/null
else
	echo "Cancelled."
fi
